### ISSUE TITLE
Silverblue not fully uninstalling previous install, can't reinstall

### ISSUE THREAD

**Issue by 13zebras** [dnkmmr69420/nix-installer-scripts#10]
I had previously used your silverblue-nix-installer script to install on silverblue (kinoite). Everything find. Then I installed `fleek`, which worked  well at first, but became corrupted. Instead of diving into home-manager and flakes, I uninstalled fleek, then uninstalled Nix using your silverblue-nix-uninstaller. I also removed a few remaining nix related files from my system.

Now I'm trying to INSTALL using silverblue-nix-installer, and I'm getting lots of errors and failure to install Nix. Attached is the output of the script:

[silverblue-nix-installer-output.txt](https://github.com/dnkmmr69420/nix-installer-scripts/files/12716790/silverblue-nix-installer-output.txt)

Any help would be appreciated. Thanks.

**Comment by dnkmmr69420** [comment]
just use the [determinate systems nix installer](https://github.com/DeterminateSystems/nix-installer) instead. It supports fedora libostree now (which means kinoite and silverblue) I should of archived this repo long ago.
