### ISSUE TITLE
Multiple "Nix Build Users"

### ISSUE THREAD

**Issue by dvogeldev** [dnkmmr69420/nix-installer-scripts#4]
Maybe I missed something in the docs. After installation via script, when logging in to uBlue-Sericea flavor of Silverblue. The sddm login screen shows +/- 20 Nix Build Users along with my standard user.

Is there a way of deleting the "Build Users"?

Thank you

**Comment by dnkmmr69420** [comment]
Nix needs the build users to work. That is a ssdm issue and it is not related to my script. Even with the offical script, there will still be those users showing up on ssdm. Use my uninstall script to remove nix and the build users.

**Comment by dvogeldev** [comment]
Yes, I can confirm this is a bug with sddm. Fix is incoming on next release per author.

https://github.com/NixOS/nix/issues/7068
