### ISSUE TITLE
Apps not updating

### ISSUE THREAD

**Issue by KimVatnedal** [dnkmmr69420/nix-installer-scripts#5]
I originally installed nix on my silverblue (bluefin) with the nix-install script included at the time, since removed I understand...

I installed Vivaldi browser version 5.7, works great, icon in the menu showing up and all.

I then updated to the new version 6.0, but when clicking the vivaldi icon in the UI, it still loads version 5.7.

Manually running Vivaldi from the terminal produces version 6.0.

The XDG_DATA_DIRS paths looks ok.

Are there some config missing or updates not happening?

Are there something misconfigured or missing from the old install script? is it safe to rerun the nix-installer-script just in case something is missing?

**Comment by dnkmmr69420** [comment]
if you use my script, type /opt/nb/reset-nix to reset nix to the default

**Comment by dnkmmr69420** [comment]
wait you need to log out then log in. I can't get the icons to automaticly update like how it does that with flatpak or regular packages.

**Comment by dnkmmr69420** [comment]
Since this is inactive, I am gonna close this
