### ISSUE TITLE
/nix/nix/nix/lib/systemd/system/nix-daemon.service No such file or directory

### ISSUE THREAD

**Issue by MC-Escherichia** [dnkmmr69420/nix-installer-scripts#6]
I had previously used your scripts without fail on two RHEL servers.  Trying to add two more to my fleet today, and both gave 

````
deleting and copying services...
cp: cannot stat ‘/nix/nix/nix/lib/systemd/system/nix-daemon.service’: No such file or directory
cp: cannot stat ‘/nix/nix/nix/lib/systemd/system/nix-daemon.socket’: No such file or directory
Enabling services...
Failed to execute operation: No such file or directory
Failed to execute operation: No such file or directory
````

during install.  The nix tool is installed but runs into permission errors.  I can't find the nix-daemon.service in /nix, so I copied it from my other machines, and updated the ExecPath and the install works fine, but I wonder if a newer version of nix requires different handling of the systemd components.

**Comment by dnkmmr69420** [comment]
I decided to make a fresh rocky linux vm (the fact it is rocky instead of RHEL should not make a difference) I could not reproduce this error. Are you sure you used the one for non muttable selinux systems?

**Comment by dnkmmr69420** [comment]
Try running it again and post the entire terminal output

**Comment by MC-Escherichia** [comment]
I ran it again on a saner server (RHEL7) and it worked as intended, I think that there are larger issues with the pair of servers I tried originally.  Sorry to bother you, appreciate the response.  Failed to reproduce.

**Comment by dnkmmr69420** [comment]
glad it works
